---
title: "Artificial Intelligence I Notes (CSC 416)"
author: Dan Wysocki
date: Fall 2014
output:
  html_document:
    toc: true
    number_sections: true
    highlight: pygments
    theme: spacelab
---

# Introduction

An *object* in Lisp is either an *atom*, a *list*, an *instance of a class*, or
other stuff (but really all you need are atoms and lists, what is this, Java?).

An *atom* is an "indecomposable" Lisp object (but just like real atoms, you
actually can decompose them).

- *integer atoms*
    - `-4`
    - `3193`
- *real atoms*
    - `3.14`
    - `000.2`
- *string atoms*
    - `"one two THREE"`
    - `" "`
    - `""`
- *symbolic atoms*
    - `R2D2`
    - `HERE-THERE-EVERYWHERE`
    - `SMALL`

The featured data type in Lisp is the *list*. A *list* is simply a sequence of
Lisp objects.

- `(2 3 5 7)`
- `(SINGLE-DIGIT-PRIMES)`
- `(1 RED 2 YELLOW 3 BLUE)`

The key to understanding Lisp programming lies in a deep understanding of
*forms*.

A *form* is an expression which can be evaluated by the Lisp interpreter.

The read-eval-print loop (REPL)
```ruby
for(ever)
  x = read()
  z = eval(x)
  print(z)
end
```

**Opening Lisp Session** (make a separate file for this and link to it)

```CommonLisp
[1]> 15
15
[2]> "Common Lisp with Objects"
"Common Lisp with Objects"
[3]> pie

*** - SYSTEM::READ-EVAL-PRINT: variable PIE has no value
The following restarts are available:
USE-VALUE      :R1      Input a value to be used instead of PIE.
STORE-VALUE    :R2      Input a new value for PIE.
ABORT          :R3      Abort main loop
Break 1 [4]> :a ; (ABORT)
[5]> pi
3.1415926535897932385L0
[6]> (+ 2 3 5 7)
17
[7]> (3 + 7)

*** - EVAL: 3 is not a function name; try using a symbol instead
The following restarts are available:
USE-VALUE      :R1      Input a value to be used instead.
ABORT          :R2      Abort main loop
Break 1 [8]> :a
[9]> (* (+ 3 6 9) (- 8 5))
54
[10]> (double 5)

*** - EVAL: undefined function DOUBLE
The following restarts are available:
USE-VALUE      :R1      Input a value to be used instead of (FDEFINITION 'DOUBLE).
RETRY          :R2      Retry
STORE-VALUE    :R3      Input a new value for (FDEFINITION 'DOUBLE).
ABORT          :R4      Abort main loop
Break 1 [11]> :a
[12]> (quote pie)
PIE
[13]> (quote (double 5))
(DOUBLE 5)
[14]> 'pie
PIE
[15]> '(double 5)
(DOUBLE 5)
[16]> (setf pie 'cherry)
CHERRY
[17]> pie
CHERRY
[18]> (setf pie apple)

*** - SETQ: variable APPLE has no value
The following restarts are available:
USE-VALUE      :R1      Input a value to be used instead of APPLE.
STORE-VALUE    :R2      Input a new value for APPLE.
ABORT          :R3      Abort main loop
Break 1 [19]> :a
[20]> (setf dozen 12)
12
[21]> dozen
12
[22]> (defun double (x) (* x 2))
DOUBLE
[23]> (double 5)
10
[24]> (double dozen)
24
[25]> (double 'dozen)

*** - *: DOZEN is not a number
The following restarts are available:
USE-VALUE      :R1      Input a value to be used instead.
ABORT          :R2      Abort main loop
Break 1 [26]> :a
[27]> (double pi)
6.283185307179586477L0
[28]> (double pie)

*** - *: CHERRY is not a number
The following restarts are available:
USE-VALUE      :R1      Input a value to be used instead.
ABORT          :R2      Abort main loop
Break 1 [29]> :a
(bye)
```

**Constant forms**

A *constant* is an expression which evaluates to itself.

Numbers, character strings, characters, and booleans are among the most commonly
used constant forms.

- numbers
    - ...
- character strings
    - ...
- characters
    - `#\A`
    - `#\z`
    - `#\4`
- booleans
    - `(NOT NIL) => T`
    - `NIL`

**Variable forms**

A *variable* is a symbol which is denotationally bound to some Lisp object.

The symbol `PI` is pre-bound in Common Lisp.

The symbol `PIE` became a variable in the sample session once it was bound to
`CHERRY`.

Variables evaluate to the values to which they are bound.

**Standard forms**

A *standard form* is a list which represents a function application in the
following sense: the first element of the list represents a function; each
remaining element of the list represents an *unevaluated argument* to that
function.
